### PR TITLE
Kustomize version change for ppc64le,Update build_devimage.sh

### PR DESCRIPTION
**Pull request by Yogita-Kulkarni19**
#### Motivation
To build image for ppc64le architecture 

#### PR checklist

Checklist items below are applicable for development targeted to both fast and stable branches/tags
- [ ] Unit tests pass locally
- [ ] FVT tests pass locally
- [ ] If the PR adds a new container image or updates the tag of an existing image (not build within cpaas), is the corresponding change made in live-builder and cpaas-midstream to add/update the image tag in the operator CSV? Link the PRs if applicable

Checklist items below are applicable for development targeted to both fast and stable branches/tags
- [x] Tested modelmesh serving deployment with odh-manifests and ran odh-manifests-e2e tests locally

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
/ok-to-test

**Comment by Yogita-Kulkarni19** [comment]
Test fail is not due to Power specific changes made in the commit. Looking into it. Will make the necessary changes if needed.

**Comment by Yogita-Kulkarni19** [comment]
Checked the code. Test is failing for Namespace not found on cluster. This is not IBM Power specific change. Test failures are not due to code changes in the reflecting in the PR

**Comment by israel-hdez** [comment]
Closing because of inactivity.

**Pull request closed without merging**
