### PR TITLE
Update quickstart to use ovms backend

### PR DESCRIPTION
**Pull request by lugi0**
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Comment by anishasthana** [comment]
@DharmitD what tests would we need to update?

**Comment by DharmitD** [comment]
> @DharmitD what tests would we need to update?

This function would need to be updated: https://github.com/lugi0/ods-ci/blob/master/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot#L75-L80

**Pull request merged**
