### PR TITLE
Add pod anti-affinity to odh-model-controller manifests

### PR DESCRIPTION
**Pull request by israel-hdez**
#### Motivation

See https://github.com/opendatahub-io/odh-model-controller/pull/51

#### PR checklist

Checklist items below are applicable for development targeted to both fast and stable branches/tags
- [x] Unit tests pass locally
- [x] FVT tests pass locally
- [ ] If the PR adds a new container image or updates the tag of an existing image (not build within cpaas), is the corresponding change made in live-builder and cpaas-midstream to add/update the image tag in the operator CSV? Link the PRs if applicable

Checklist items below are applicable for development targeted to both fast and stable branches/tags
- [ ] Tested modelmesh serving deployment with odh-manifests and ran odh-manifests-e2e tests locally

### CODE REVIEW

**Comment by Jooho** [comment]
@israel-hdez this looks good to me. Could you please create another PR for the release branch? stable related folder must be synced with release branch too.

**Comment by israel-hdez** [comment]
> Could you please create another PR for the release branch? stable related folder must be synced with release branch too.

This PR is covering both folders :-)

**Comment by Jooho** [comment]
I know but the stable folder will be used for deploying stable images in the stable branch as well so it should be synced with stable branch as well

**Comment by israel-hdez** [comment]
> I know but the stable folder will be used for deploying stable images in the stable branch as well so it should be synced with stable branch as well

Hmmm... I think I understand.
I see two branches: `release-v0.11.0-alpha` and `release-v0.11.0-rc0`. The `alpha` one is the correct one, right?

**Comment by Jooho** [comment]
Correct. I will remove the other.

**Comment by israel-hdez** [comment]
> Could you please create another PR for the release branch? stable related folder must be synced with release branch too.

@Jooho Here is the PR: #120

**Review by Jooho — DISMISSED** [review]
/lgtm

**Comment by Jooho** [comment]
You should change openshift-ci build-root part : https://github.com/openshift/release/pull/40548/files#r1239020973

**Review by Jooho — APPROVED** [review]
/lgtm

**Pull request merged**
