### PR TITLE
Update images to latest tags

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Comment by anishasthana** [comment]
cc @Xaenalt

**Comment by anishasthana** [comment]
On curling in a deployment:
```
❯ curl -k https://$ROUTE/infer -d @input.json -H "Authorization: Bearer $TOKEN"
{"model_name":"example-onnx-mnist__isvc-b29c3d91f3","model_version":"1","outputs":[{"name":"Plus214_Output_0","datatype":"FP32","shape":[1,10],"data":[-8.233053,-7.7497034,-3.4236815,12.3630295,-12.079103,17.266596,-10.570976,0.7130762,3.321715,1.3621228]}]}
```

**Comment by Xaenalt** [comment]
Saw in action, looks good to me
/lgtm

**Pull request merged**
